# Opcjonalna konfiguracja bazy MySQL na dockerze
# Używana zamiast oddzielnej instalacji serwera MySQL
# W celu uruchomienia należy wywołać komendę z linii poleceń w tym katalogu:
# docker-compose up

# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: toor
    volumes:
      - 'tin-mysql:/var/lib/mysql'

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 18080:18080
volumes:
  tin-mysql: